server:
  port: 8080

spring:
  datasource:
    username: root
    password: s002611
    url: jdbc:mysql://localhost:3306/dag?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
    encoding: UTF-8

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: dag.pojo